In [7]:
# 1. Import the numpy package under the name np
import numpy as np

In [9]:
# Print the numpy version and the configuration
numpy --version

NameError: name 'numpy' is not defined

In [17]:
# Create a null vector of size 10
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
# How to find the memory size of any array
null_vector.size

10

In [23]:
# How to get the documentation of the numpy add function 
np.add?


Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\techforafrica\anaconda3\envs\environ\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    co

In [24]:
# How to get the documentation of the numpy add function 
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [25]:
# Create a null vector of size 10 but the fifth value which is 1
vector = np.zeros(10)
vector[4] = 1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [27]:
# Create a vector with values ranging from 10 to 49
range_value  = np.arange(10, 50)
range_value


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [30]:
# Reverse a vector (first element becomes last
reverse_value = range_value[::-1]
reverse_value

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [33]:
# Create a 3x3 matrix with values ranging from 0 to 8

matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
# Find indices of non-zero elements from the given array
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)
non_zero_indices

(array([0, 1, 4], dtype=int64),)

In [38]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# Create a 3x3x3 array with random values
random_array = np.random.random((3,3,3))
random_array

array([[[0.76954036, 0.03334592, 0.12597685],
        [0.05899568, 0.37218258, 0.38467111],
        [0.52866794, 0.10904701, 0.87989891]],

       [[0.48937714, 0.86068409, 0.07096908],
        [0.0281724 , 0.34741914, 0.28093966],
        [0.68138737, 0.67859724, 0.54133563]],

       [[0.24471739, 0.47425719, 0.99619252],
        [0.45919641, 0.5548131 , 0.97497967],
        [0.25386364, 0.07956358, 0.61526409]]])

In [51]:
# Create a 10x10 array with random values and find the minimum and maximum values
rand_value = np.random.random((10,10))
np.min(rand_value)


0.005596168130731383

In [52]:
np.max(rand_value)

0.9850555221718903

In [56]:
random_vector = np.random.random(30)
np.mean(random_vector)

0.4502326741365043

In [57]:
# Create a 2d array with 1 on the border and 0 inside
array_with_border = np.ones((5,5))
array_with_border

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
array_with_border[1:4, 1:4] = 0
array_with_border

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
# How to add a border (filled with 0's) around an existing array?
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
array = np.random.random((3,4))
array

array([[0.49344824, 0.77400481, 0.22638934, 0.84473989],
       [0.24453549, 0.77567336, 0.49723953, 0.57912753],
       [0.83756672, 0.31685192, 0.51022676, 0.41759444]])

In [76]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [79]:
border_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
border_array

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

In [87]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
array = np.array([1,2,3,4])
matrix = np.diag(array, k=-1)
matrix


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])