In [7]:
# 1. Import the numpy package under the name np
import numpy as np

In [1]:
import numpy as np

print("NumPy Version:", np.__version__)
print("NumPy Configuration:")
print(np.show_config())


NumPy Version: 1.26.3
NumPy Configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/TechForAfrica/anaconda3/envs/environ/Library/include
    lib directory: C:/Users/TechForAfrica/anaconda3/envs/environ/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_16b2j7ad8n\croot\numpy_and_numpy_base_1704311752418\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1607375931856
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.3
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.6
Machine Information:
  build:
    cp

In [17]:
# Create a null vector of size 10
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
# How to find the memory size of any array
null_vector.size

10

In [23]:
help(np.add)



Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\techforafrica\anaconda3\envs\environ\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    co

In [2]:
# How to get the documentation of the numpy add function 
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [25]:
# Create a null vector of size 10 but the fifth value which is 1
vector = np.zeros(10)
vector[4] = 1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [27]:
# Create a vector with values ranging from 10 to 49
range_value  = np.arange(10, 50)
range_value


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [30]:
# Reverse a vector (first element becomes last
reverse_value = range_value[::-1]
reverse_value

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [33]:
# Create a 3x3 matrix with values ranging from 0 to 8

matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
# Find indices of non-zero elements from the given array
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)
non_zero_indices

(array([0, 1, 4], dtype=int64),)

In [38]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# Create a 3x3x3 array with random values
random_array = np.random.random((3,3,3))
random_array

array([[[0.76954036, 0.03334592, 0.12597685],
        [0.05899568, 0.37218258, 0.38467111],
        [0.52866794, 0.10904701, 0.87989891]],

       [[0.48937714, 0.86068409, 0.07096908],
        [0.0281724 , 0.34741914, 0.28093966],
        [0.68138737, 0.67859724, 0.54133563]],

       [[0.24471739, 0.47425719, 0.99619252],
        [0.45919641, 0.5548131 , 0.97497967],
        [0.25386364, 0.07956358, 0.61526409]]])

In [51]:
# Create a 10x10 array with random values and find the minimum and maximum values
rand_value = np.random.random((10,10))
np.min(rand_value)


0.005596168130731383

In [52]:
np.max(rand_value)

0.9850555221718903

In [56]:
random_vector = np.random.random(30)
np.mean(random_vector)

0.4502326741365043

In [57]:
# Create a 2d array with 1 on the border and 0 inside
array_with_border = np.ones((5,5))
array_with_border

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
array_with_border[1:4, 1:4] = 0
array_with_border

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
# How to add a border (filled with 0's) around an existing array?
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
array = np.random.random((3,4))
array

array([[0.49344824, 0.77400481, 0.22638934, 0.84473989],
       [0.24453549, 0.77567336, 0.49723953, 0.57912753],
       [0.83756672, 0.31685192, 0.51022676, 0.41759444]])

In [76]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [79]:
border_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
border_array

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

In [87]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
array = np.array([1,2,3,4])
matrix = np.diag(array, k=-1)
matrix


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [3]:
import numpy as np


matrix = np.zeros((8, 8))

# Fill the even rows with 1s 
matrix[::2, ::2] = 1

# Fill the odd rows with 1s
matrix[1::2, 1::2] = 1

matrix


array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [4]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
import numpy as np

shape = (6, 7, 8)
index_100 = np.unravel_index(99, shape)
index_100

(1, 5, 3)

In [5]:
# Create a checkerboard 8x8 matrix using the tile function
import numpy as np


tile = np.array([[0, 1], [1, 0]])


checkerboard = np.tile(tile, (4, 4))

checkerboard


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
from sklearn.preprocessing import normalize

# Create a 5x5 random matrix
random_matrix = np.random.random((5, 5))

# Normalize the matrix
normalized_matrix = normalize(random_matrix)

normalized_matrix


In [7]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA) 
import numpy as np

# Define the custom dtype for RGBA color
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

# Example usage
color = np.array([(255, 0, 0, 255)], dtype=color_dtype)
print(color)


[(255, 0, 0, 255)]


In [10]:
import numpy as np

# Create the 5x3 matrix
matrix1 = np.random.random((5, 3))

# Create the 3x2 matrix
matrix2 = np.random.random((3, 2))

# Multiply the matrices
result = np.dot(matrix1, matrix2)


result


array([[0.78149261, 0.35801967],
       [0.79562406, 0.53496556],
       [0.6300865 , 0.53780476],
       [0.77667119, 0.3754094 ],
       [0.93909515, 0.37938227]])

In [14]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Negate elements between 3 and 8
arr[(arr > 3) & (arr < 8)] *= -1

# Print the modified array
print(arr)


[ 1  2  3 -4 -5 -6 -7  8  9 10]


In [16]:
# What is the output of the following script?
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [24]:
# Consider an integer vector Z, which of these expressions are legal?

Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Z**Z # legal
# 2 << Z >> 2 # not legal
Z <- Z # legal
1j*Z  # legal
Z/1/1 #legal
# Z<Z>Z not legal

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])