In [2]:
import numpy as np

In [5]:
a = np.array([1,3,4,5,6])
a.shape

(5,)

In [7]:
type(a)

numpy.ndarray

In [9]:
a = [2,3,4,6]
type(a)

list

In [11]:
arr = np.array([[2,3,4,5], [5,6,7,8]])
arr.shape

(2, 4)

In [12]:
my_array = np.array(1_000_000)


In [13]:
%time my_array2 = my_array * 2

CPU times: total: 15.6 ms
Wall time: 51 ms


In [15]:
my_list = list(range(1_000_000))
%time my_list2 = [x * 2 for x in my_list]

CPU times: total: 391 ms
Wall time: 518 ms


# The NumPy ndarray: A Multidimensional Array Object

In [16]:
import numpy as np

In [17]:
a = np.array([1,2,4])

In [19]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.7]])

In [20]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.7]])

In [21]:
data.shape

(2, 3)

In [23]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  67.]])

In [24]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13.4]])

In [25]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.7]])

In [26]:
data.shape

(2, 3)

In [27]:
data.ndim

2

In [28]:
a = [1,2,3]
type(a)

list

In [29]:
type(data)

numpy.ndarray

In [30]:
data.dtype

dtype('float64')

In [31]:
data.size

6

# Creating ndarrays

In [32]:
data1 = [6, 7.5, 8, 0, 1]

In [35]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [36]:
data2 = [[1,2,3,4], [5,6,7,8,]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
arr2.ndim

2

In [38]:
arr1.ndim

1

In [39]:
arr2.shape

(2, 4)

In [40]:
arr1.dtype

dtype('float64')

In [41]:
arr2.dtype

dtype('int32')

In [42]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [44]:
np.empty((2,3,2))

array([[[1.24324094e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.03977794e-312, 4.15770674e-061]],

       [[9.39412841e+165, 3.76966381e-061],
        [5.98248981e+174, 3.40610470e-057],
        [2.47147518e-056, 1.74212421e+184]]])

In [46]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [48]:
arr1.dtype

dtype('float64')

In [49]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [50]:
arr2.dtype

dtype('int32')

In [52]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [54]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [55]:
float_arr.dtype

dtype('float64')

In [57]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [58]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [59]:
arr.dtype

dtype('float64')

In [60]:
numeric_string = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [61]:
numeric_string.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [63]:
int_array = np.arange(10)
int_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
int_array.dtype

dtype('int32')

In [69]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [73]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [74]:
zeros_unit32 = np.zeros(8, dtype="u4")

# Arithmetic with NumPy Arrays (Vectorization)

In [76]:
arr = np.array([[1., 2., 3.], [4., 5., 6]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [77]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [78]:
arr  - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [79]:
1 / arr 

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

# Arithmetic operations with scalars

In [80]:
arr 

array([[1., 2., 3.],
       [4., 5., 6.]])

In [81]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [83]:
arr2 = np.array([[0., 4., 1.], [7., 2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

# Comparisons between arrays

In [84]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

# Basic Indexing and Slicing

In [85]:
import numpy as np

In [87]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a = np.array([5, 6,7,9,1])

In [89]:
a[0]

5

In [90]:
arr[1]

1

In [91]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
arr[5:8]

array([5, 6, 7])

In [93]:
arr[5:8] = 12

In [94]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [95]:
arr[5:8]

array([12, 12, 12])

In [96]:
arr_slice = arr[5:8]

In [97]:
arr_slice

array([12, 12, 12])

In [99]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [100]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [101]:
arr_slice[:] = 64

In [102]:
arr_slice

array([64, 64, 64])

In [103]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [105]:
arr_slice_copy = arr[5:8].copy
arr_slice_copy

<function ndarray.copy>

In [106]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

# Higher Dimentional Arrays

In [107]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [108]:
arr2d[2]

array([7, 8, 9])

In [109]:
arr2d[0, 2]

3

In [110]:
arr2d[0][2]

3

In [113]:
samples = np.random.standard_normal(size=(4, 4))

In [114]:
samples

array([[-0.1144817 , -0.16234371, -1.37137791, -1.48526948],
       [ 0.17007646,  2.19681594, -0.34634824, -1.42337996],
       [-0.65155815,  0.77436457, -1.05606308,  0.93694038],
       [ 0.28875558,  0.7712103 , -0.12406108, -0.01765177]])

In [115]:
# seed` determines initial state of generator

rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))
data

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

# Unary

In [117]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [119]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

# Binary

In [120]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)

In [121]:
x

array([-1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,  2.34740965,
        0.96849691, -0.75938718,  0.90219827])

In [122]:
y

array([-0.46695317, -0.06068952,  0.78884434, -1.25666813,  0.57585751,
        1.39897899,  1.32229806, -0.29969852])

In [123]:
np.maximum(x, y)

array([-0.46695317,  0.6488928 ,  0.78884434, -1.25666813,  2.34740965,
        1.39897899,  1.32229806,  0.90219827])

In [129]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:

np.add(arr, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Expressing Conditional Logic as Array Operations

In [133]:
np.add(arr, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])